startup_commands = [
  "setxkbmap -layout us,ru,pl -option grp:alt_space_toggle",
  "alacritty",
]

################################################################

[window]
minimum_width_tiling = 10
default_width_tiling = 0.324

[window.border]
size = 2
color_inactive = "#2b2b29"
color_active = "#a38b43"

[workspaces]
count = 9
outer_gap_horiz = 10
outer_gap_vert = 10
inner_gap = 5

################################################################

[[keybindings]]
keys_combination = "Alt+Return"
action = "exec"
arguments = ["alacritty"]

#############################################################

[[keybindings]]
keys_combination = "Alt+H"
action = "exec"
arguments = ["target/debug/wm_msg focus left"]

[[keybindings]]
keys_combination = "Alt+L"
action = "exec"
arguments = ["target/debug/wm_msg focus right"]

[[keybindings]]
keys_combination = "Alt+J"
action = "exec"
arguments = ["target/debug/wm_msg focus up"]

[[keybindings]]
keys_combination = "Alt+K"
action = "exec"
arguments = ["target/debug/wm_msg focus down"]

#############################################################

[[keybindings]]
keys_combination = "Alt+Ctrl+H"
action = "exec"
arguments = ["target/debug/wm_msg move left"]

[[keybindings]]
keys_combination = "Alt+Ctrl+L"
action = "exec"
arguments = ["target/debug/wm_msg move right"]

#############################################################

[[keybindings]]
keys_combination = "Alt+Shift+H"
action = "exec"
arguments = ["target/debug/wm_msg grow width 16"]

[[keybindings]]
keys_combination = "Alt+Shift+L"
action = "exec"
arguments = ["target/debug/wm_msg shrink width 16"]

#############################################################

[[keybindings]]
keys_combination = "Alt+1"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 1"]

[[keybindings]]
keys_combination = "Alt+2"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 2"]

[[keybindings]]
keys_combination = "Alt+3"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 3"]

[[keybindings]]
keys_combination = "Alt+4"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 4"]

[[keybindings]]
keys_combination = "Alt+5"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 5"]

[[keybindings]]
keys_combination = "Alt+6"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 6"]

[[keybindings]]
keys_combination = "Alt+7"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 7"]

[[keybindings]]
keys_combination = "Alt+8"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 8"]

[[keybindings]]
keys_combination = "Alt+9"
action = "exec"
arguments = ["target/debug/wm_msg workspace change 9"]

################################################################
