#!/bin/sh

xrandr -s 5120x1440

# picom --config ~/.config/i3/picom.conf &

export RUST_LOG="trace"
export RUST_BACKTRACE=1

LOG_FILE="$HOME/.local/state/x11_wm_rust.log"

mkdir -p "$(dirname "$LOG_FILE")"
rm -rf "$LOG_FILE"

# Explanation:
#   - starts window manager.
#   - '2>&1' redirects stderr (file descriptor 2) to stdout (file descriptor 1).
#     This merges both streams so we can pipe them together.
#   - '|' (pipe) sends the combined stdout/stderr to the 'tee' command.
#   - 'tee -a "$LOG_FILE"' appends ('-a') the input to log file AND
#     also prints it to its own stdout, which SDDM will then capture in its
#     default xorg-session.log.
exec /usr/local/bin/x11_wm_rust 2>&1 | tee -a "$LOG_FILE"